config/routes.rb
Rails.application.routes.draw do
  resources :ticket_offerings

  resources :bookings

  root to: "movie_theaters#show"

  resources :tickets

  resources :movies

  resources :showings

  resources :screening_rooms

  resources :movie_theaters
    get '/manage_theater_dashboard/:id',  :as => :theater_dashboard,
                                          :controller => :movie_theaters,
                                          :action => :dashboard

    get '/sales_information/:id',         :as => :sales_information,
                                          :controller => :movie_theaters,
                                          :action => :sales_dashboard

end

app/models/movie_theater.rb
class MovieTheater < ActiveRecord::Base
  has_many :screening_rooms

  has_many :showings, :through => :screening_rooms
  has_many :movies, :through => :showings
  has_many :bookings, :through => :showings
  has_many :tickets_sold, :through => :bookings, :source => :tickets

  has_many :ticket_offerings

  def revenue
    self.bookings.sum(:total_cost)
  end

  def movies
  end

end

app/controllers/movie_theaters_controller.rb
class MovieTheatersController < ApplicationController
  before_action :set_movie_theater, only: [:edit, :update, :destroy, :dashboard, :sales_dashboard]

  def dashboard
  end

  def sales_dashboard
    if params[:movie_filter].present? && params[:movie_filter] != "All"
      @movie_id = params[:movie_filter]
      @bookings = @movie_theater.bookings.where(:movie_id => params[:movie_filter])
    else
      @movie_id = "All"
      @bookings = @movie_theater.bookings
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    # FOR TESTING PURPOSES WILL ALWAYS USE FIRST
    @movie_theater = MovieTheater.first

    @day = params[:day] || Time.current.to_date
    @upcoming_dates = (Time.current.to_date..(Time.current.to_date + 6.days)).map{ |date| date }
    @showings = @movie_theater.showings.where(:date => @day)
    @movies = Movie.find(@showings.pluck(:movie_id))
  end

  def edit
  end

  def create
    @movie_theater = MovieTheater.new(movie_theater_params)

    respond_to do |format|
      if @movie_theater.save
        format.html { redirect_to @movie_theater, notice: 'Movie theater was successfully created.' }

      else
        format.html { render :new }

      end
    end
  end

  def update
    respond_to do |format|
      if @movie_theater.update(movie_theater_params)
        format.html { redirect_to theater_dashboard_url(@movie_theater), notice: 'Movie theater was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @movie_theater.destroy
    respond_to do |format|
      format.html { redirect_to movie_theaters_url, notice: 'Movie theater was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_theater
      @movie_theater = MovieTheater.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_theater_params
      params.require(:movie_theater).permit(:name, :address_1, :address_2, :city, :state, :zip, :phone)
    end
end

app/helpers/movie_theaters_helper.rb
module MovieTheatersHelper
end

app/views/movie_theaters/_date_selection.html.erb
<ul class="list-inline dates-list">
  <% @upcoming_dates.each do |day| %>
    <li class="text-center">
      <%= link_to movie_theater_path(@movie_theater, :day => day) do %>
        <h2 class="date" id="<%= day %>">
          <% if day === Date.current %>
            Today<br>
            <small class="no-margin-top">
              <em>&nbsp </em>
            </small>
          <% else %>
            <%= day.strftime("%b %d") %><br>
            <small class="no-margin-top">
              <em><%= day.strftime("%A") %></em>
            </small>
          <% end %>
        </h2>
      <% end %>
    </li>
  <% end %>
</ul>
<hr/>

<script type="text/javascript">
  $( document ).ready(function() {
    $('#<%= @day %>').addClass('active');
  });
</script>

app/views/movie_theaters/_form.html.erb
<%= form_for(@movie_theater, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @movie_theater.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@movie_theater.errors.count, "error") %> prohibited this movie_theater from being saved:</h4>

      <ul>
      <% @movie_theater.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address_1, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address_1, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address_2, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address_2, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zip, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :zip, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn time-button" %>
    </div>
  </div>
<% end %>

app/views/movie_theaters/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="movie-app-page-header">
        <h1>
          Manage Your Theater
        </h1>
      </div>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <%= link_to sales_information_path(@movie_theater), class: 'btn time-button' do %>
        View Sales Information
      <% end %>
      <div class="row">
        <br>
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                General Information
                <%= link_to edit_movie_theater_path(@movie_theater) do %>
                  <%= icon('fa fa-pencil pull-right') %>
                <% end %>
              </h3>
            </div>

            <ul class="list-group">
              <li class="list-group-item"><%= @movie_theater.name %></li>
              <li class="list-group-item">
                <%= @movie_theater.address_1 %>
                <% if @movie_theater.address_2.present? %>
                , <%= @movie_theater.address_2 %>
                <% end %>
              </li>
              <li class="list-group-item">
                <%= @movie_theater.city %>, <%= @movie_theater.state %> <%= @movie_theater.zip %>
              </li>
              <li class="list-group-item">
                <%= @movie_theater.phone %>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                Screening Rooms
                <%= link_to screening_rooms_url do %>
                  <%= icon('fa fa-pencil pull-right') %>
                <% end %>
              </h3>
            </div>

            <ul class="list-group">
              <% @movie_theater.screening_rooms.each do |room| %>
              <li class="list-group-item">
                Theater #<%= room.theater_number %> | <%= room.seat_quantity %> seat capacity
              </li>
              <% end %>
            </ul>
          </div>
        </div>

        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                Types of Tickets
                <%= link_to ticket_offerings_url do %>
                  <%= icon('fa fa-pencil pull-right') %>
                <% end %>
              </h3>
            </div>
            <ul class="list-group">
              <% @movie_theater.ticket_offerings.each do |ticket| %>
              <li class="list-group-item">
                <%= ticket.name %> | <%= number_to_currency(ticket.price) %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movie_theaters/edit.html.erb
<div class="conatiner">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="movie-app-page-header">
        <h1>
          Update Theater Information
        </h1>
      </div>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/movie_theaters/sales_dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="movie-app-page-header">
        <h1>
          Sales Information
        </h1>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="row">
        <div class="col-md-4">
          <div class="sales-info-box">
            <h5 class="sales-type">Total Revenue</h5>
            <h2 class="sales-number"><%= number_to_currency(@movie_theater.revenue) %></h2>
          </div>
        </div>
        <div class="col-md-4">
          <div class="sales-info-box">
            <h5 class="sales-type">Total Tickets Sold</h5>
            <h2 class="sales-number"><%= @movie_theater.tickets_sold.count %></h2>
          </div>
        </div>
        <div class="col-md-4">
          <div class="sales-info-box">
            <h5 class="sales-type">Total Transactions</h5>
            <h2 class="sales-number"><%= @movie_theater.bookings.count %></h2>
          </div>
        </div>
      </div>
    </div>
  </div>

  <br>
  <br>

  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <h2>
        Order Information
      </h2>
      <hr/>
      <div class="row">
        <div class="col-md-4">
          <%= form_tag( sales_information_url(@movie_theater), class: 'form', :remote => true) do %>
            <%= select_tag :movie_filter,
              content_tag(:option,'All Movies',:value=>"All") +
              options_from_collection_for_select(Movie.all,
              'id', 'name', @movie_id.to_s), {:class => 'form-control'} %>
          <% end %>
        </div>
      </div>
      <div class="table-responsive">
        <br>


        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>Booking Id</th>
              <th>Movie</th>
              <th>Number of Tickets</th>
              <th>Total Purchase</th>
              <th>Buyer Email</th>
            </tr>
          </thead>

          <tbody id="bookings-list">
            <%= render @bookings %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    $('#movie_filter').change(function() {
      $.ajax({
          url: '/sales_information/<%= @movie_theater.id %>',
          type: 'GET',
          dataType: 'script',
          data: {movie_filter: $('#movie_filter').val()}
        })
    });
  });
</script>

app/views/movie_theaters/sales_dashboard.js.erb
$("#bookings-list").hide();
$("#bookings-list").html("<%= j render(:partial => @bookings) %>");
$("#bookings-list").fadeIn('slow');

app/views/movie_theaters/show.html.erb
<div class="ignore-container movie-theater-landing">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1">
        <h1><%= @movie_theater.name %></h1>
        <h4 class="contact-info">
          <%= @movie_theater.address_1 %>, <%= @movie_theater.address_2 %>,
          <%= @movie_theater.city %>, <%= @movie_theater.state %> <%= @movie_theater.zip %> |
          <%= @movie_theater.phone %>
        </h4>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <%= render 'date_selection', :@upcoming_dates => @upcoming_dates %>
    </div>
  </div>

  <div class="row">
    <%= render 'movies/current_playing_index', :@movies => @movies %>
  </div>
</div>