config/routes.rb
Rails.application.routes.draw do
  resources :ticket_offerings

  resources :bookings

  root to: "movie_theaters#show"

  resources :tickets

  resources :movies

  resources :showings

  resources :screening_rooms

  resources :movie_theaters
    get '/manage_theater_dashboard/:id',  :as => :theater_dashboard,
                                          :controller => :movie_theaters,
                                          :action => :dashboard

    get '/sales_information/:id',         :as => :sales_information,
                                          :controller => :movie_theaters,
                                          :action => :sales_dashboard

end

app/models/showing.rb
class Showing < ActiveRecord::Base
  default_scope { order('time_slot ASC') }
  scope :upcoming_shows, -> { where( is_show_upcoming: true ) }

  belongs_to :screening_room
  has_one :movie_theater, :through => :screening_room

  belongs_to :movie
  has_many :tickets
  has_many :bookings

  before_save :set_date

  def amount_of_seats_remaining
    self.screening_room.seat_quantity - self.tickets.count
  end

  def check_seat_availability
    if self.amount_of_seats_remaining <= 0
      self.seats_available = false
      self.save
    end
  end

  def set_date
    self.date = self.time_slot.to_date
  end

end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
  before_action :set_showing, only: [:show, :edit, :update, :destroy, :confirm_tickets_available]
  before_action :confirm_tickets_available, only: [:show]

  # GET /showings
  # GET /showings.json
  def index
    @showings = Showing.all
  end

  # GET /showings/1
  # GET /showings/1.json
  def show
  end

  # GET /showings/new
  def new
    @showing = Showing.new
  end

  # GET /showings/1/edit
  def edit
  end

  # POST /showings
  # POST /showings.json
  def create
    @showing = Showing.new(showing_params)

    respond_to do |format|
      if @showing.save
        format.html { redirect_to @showing, notice: 'Showing was successfully created.' }
        format.json { render :show, status: :created, location: @showing }
      else
        format.html { render :new }
        format.json { render json: @showing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /showings/1
  # PATCH/PUT /showings/1.json
  def update
    respond_to do |format|
      if @showing.update(showing_params)
        format.html { redirect_to @showing, notice: 'Showing was successfully updated.' }
        format.json { render :show, status: :ok, location: @showing }
      else
        format.html { render :edit }
        format.json { render json: @showing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showings/1
  # DELETE /showings/1.json
  def destroy
    @showing.destroy
    respond_to do |format|
      format.html { redirect_to showings_url, notice: 'Showing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showing
      @showing = Showing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def showing_params
      params.require(:showing).permit(:time_slot, :seats_available, :screening_room_id, :movie_id)
    end

    def confirm_tickets_available
      if @showing.amount_of_seats_remaining <= 0
        redirect_to :back, :notice => "Sorry this show is sold out!"
      elsif @showing.time_slot < Time.current
        redirect_to :back, :notice => "Purchasing tickets for this show has closed."
      end
      rescue ActionController::RedirectBackError
        redirect_to root_path
    end
end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/views/showings/_available_showings_buttons.html.erb
<% @showings.where(:movie_id => movie.id).each do |showing| %>
  <% if showing.seats_available? && showing.time_slot > Time.now %>

    <%= link_to showing, class: "btn btn-lg time-button" do %>
      <%= showing.time_slot.strftime('%I:%M %p') %>
    <% end %>

  <% else %>

    <%= link_to showing, class: "btn btn-lg time-button", disabled: "disabled" do %>
      <%= showing.time_slot.strftime('%I:%M %p') %>
    <% end %>

  <% end %>
<% end %>

app/views/showings/_available_showings_buttons_mobile.html.erb
<% @showings.where(:movie_id => movie.id).each do |showing| %>
  <% if showing.seats_available? && showing.time_slot > Time.current %>

    <%= link_to showing, class: "btn time-button" do %>
      <%= showing.time_slot.strftime('%I:%M %p') %>
    <% end %>

  <% else %>

    <%= link_to showing, class: "btn time-button", disabled: "disabled" do %>
      <%= showing.time_slot.strftime('%I:%M %p') %>
    <% end %>

  <% end %>
<% end %>

app/views/showings/_checkout_box.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Purchase</h3>
  </div>
  <div class="panel-body">
    <%= submit_tag "Checkout", class: "btn btn-lg btn-block time-button" %>
  </div>
</div>

app/views/showings/_form.html.erb
<%= form_for(@showing, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @showing.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@showing.errors.count, "error") %> prohibited this showing from being saved:</h4>

      <ul>
      <% @showing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :time_slot, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :time_slot, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :seats_available, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :seats_available, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :screening_room_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :screening_room_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :movie_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :movie_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/showings/_movie_showing_information.html.erb
<div class="row hidden-xs">
  <div class="col-xs-12">
    <%= image_tag @showing.movie.image_url, height: 150 %>
    <h4>
      <strong><%= @showing.movie.name %></strong>
    </h4>
    <h5>Rated <%= @showing.movie.rating %></h5>
    <h5><%= @showing.time_slot.strftime('%b %d at %I:%M %p') %></h5>
    <h5><%= @showing.screening_room.movie_theater.name %></h5>
    <h5>Theater #<%= @showing.screening_room.theater_number %></h5>
    <h5><em><%= @showing.amount_of_seats_remaining %> seats remaining</em></h5>
  </div>
</div>

<div class="row visible-xs">
  <div class="col-xs-4">
    <%= image_tag @showing.movie.image_url, class: 'img-responsive' %>
    <h4>
  </div>
  <div class="col-xs-8">
    <h4 class="no-margin-top">
      <strong><%= link_to @showing.movie.name, @showing.movie %></strong>
    </h4>
    <h5>Rated <%= @showing.movie.rating %></h5>
    <h5><%= @showing.time_slot.strftime('%b %d at %I:%M %p') %></h5>
    <h5><%= @showing.screening_room.movie_theater.name %></h5>
    <h5>Theater #<%= @showing.screening_room.theater_number %> | <em><%= @showing.amount_of_seats_remaining %> seats left</em></h5>
  </div>
</div>
<hr/>

app/views/showings/_ticket_selection.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">How many tickets would you like?</h3>
  </div>
  <div class="panel-body">
    <% @showing.movie_theater.ticket_offerings.each do |ticket_type| %>
    <div class="row">
      <div class="col-xs-6 col-md-6 text-center">
        <p>
          <strong><%= ticket_type.name %></strong>
        </p>
        <p><%= number_to_currency(ticket_type.price) %> x</p>
      </div>
      <div class="col-xs-6 col-md-6 text-center">
        <p>
          <strong>Quantity</strong>
        </p>
        <p>
        <div class="form-group text-center">
          <%= select_tag "tickets[#{ticket_type.id}]", options_for_select(0..@showing.amount_of_seats_remaining), {:class => 'form-control'} %>
        </div>
        </p>
      </div>
    </div>
    <hr/>
    <% end %>
  </div>
</div>

app/views/showings/edit.html.erb
<div class="page-header">
  <%= link_to showings_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @showing, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing showing</h1>
</div>

<%= render 'form' %>

app/views/showings/index.html.erb
<div class="page-header">
  <%= link_to new_showing_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Showing
  <% end %>
  <h1>Listing showings</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Time slot</th>
            <th>Seats available</th>
            <th>Screening room</th>
            <th>Movie</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @showings) do |showing| %>
            <td><%= showing.time_slot %></td>
            <td><%= showing.seats_available %></td>
            <td><%= showing.screening_room_id %></td>
            <td><%= showing.movie_id %></td>
            <td><%= link_to 'Show', showing %></td>
        <td><%= link_to 'Edit', edit_showing_path(showing) %></td>
        <td><%= link_to 'Destroy', showing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/showings/new.html.erb
<div class="page-header">
  <%= link_to showings_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New showing</h1>
</div>

<%= render 'form' %>

app/views/showings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="movie-app-page-header">
        <h1>Checkout</h1>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="row">
        <div class="col-md-2">
          <%= render 'movie_showing_information' %>
        </div>
        <%= form_tag(new_booking_url, method: :get) do %>
          <%= hidden_field_tag :showing_id, @showing.id %>
          <div class="col-md-6">
            <%= render 'ticket_selection' %>
          </div>
          <div class="col-md-4">
            <%= render 'checkout_box' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>