config/routes.rb
Rails.application.routes.draw do
  resources :ticket_offerings

  resources :bookings

  root to: "movie_theaters#show"

  resources :tickets

  resources :movies

  resources :showings

  resources :screening_rooms

  resources :movie_theaters
    get '/manage_theater_dashboard/:id',  :as => :theater_dashboard,
                                          :controller => :movie_theaters,
                                          :action => :dashboard

    get '/sales_information/:id',         :as => :sales_information,
                                          :controller => :movie_theaters,
                                          :action => :sales_dashboard

end

app/models/screening_room.rb
class ScreeningRoom < ActiveRecord::Base
  validates_presence_of :movie_theater, :theater_number, :seat_quantity

  belongs_to :movie_theater
  has_many :showings
end

app/controllers/screening_rooms_controller.rb
class ScreeningRoomsController < ApplicationController
  before_action :set_screening_room, only: [:show, :edit, :update, :destroy]

  # GET /screening_rooms
  # GET /screening_rooms.json
  def index
    @screening_rooms = ScreeningRoom.all
    @screening_room = ScreeningRoom.new
  end

  # GET /screening_rooms/1
  # GET /screening_rooms/1.json
  def show
  end

  # GET /screening_rooms/new
  def new
    @screening_room = ScreeningRoom.new
  end

  # GET /screening_rooms/1/edit
  def edit
  end

  # POST /screening_rooms
  # POST /screening_rooms.json
  def create
    @screening_room = ScreeningRoom.new(screening_room_params)

    respond_to do |format|
      if @screening_room.save
        format.html { redirect_to screening_rooms_url, notice: 'Screening room was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /screening_rooms/1
  # PATCH/PUT /screening_rooms/1.json
  def update
    respond_to do |format|
      if @screening_room.update(screening_room_params)
        format.html { redirect_to screening_rooms_url, notice: 'Screening room was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /screening_rooms/1
  # DELETE /screening_rooms/1.json
  def destroy
    @screening_room.destroy
    respond_to do |format|
      format.html { redirect_to screening_rooms_url, notice: 'Screening room was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screening_room
      @screening_room = ScreeningRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def screening_room_params
      params.require(:screening_room).permit(:theater_number, :seat_quantity, :movie_theater_id)
    end
end

app/helpers/screening_rooms_helper.rb
module ScreeningRoomsHelper
end

app/views/screening_rooms/_form.html.erb
<%= form_for(@screening_room, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @screening_room.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@screening_room.errors.count, "error") %> prohibited this screening_room from being saved:</h4>

      <ul>
      <% @screening_room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :theater_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :theater_number, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :seat_quantity, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :seat_quantity, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :movie_theater_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :movie_theater_id,
        options_from_collection_for_select(MovieTheater.all,'id', 'name'),
        {},
        {:class => 'form-control'} %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn time-button" %>
      <% if @screening_room.persisted? %>
        <%= link_to "Delete Screening Room", @screening_room, method: :delete,
            class: "btn time-button", data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/screening_rooms/_screening_room.html.erb
<li class="list-group-item">
  Theater #<%= screening_room.theater_number %> | <%= screening_room.seat_quantity %> seats
  <%= link_to edit_screening_room_url(screening_room) do %>
    <%= icon('fa fa-pencil pull-right') %>
  <% end %>
</li>

app/views/screening_rooms/edit.html.erb
<div class="conatiner">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="movie-app-page-header">
        <h1>
          Edit Theater #<%= @screening_room.theater_number %>
        </h1>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <%= render 'form' %>
    </div>
  </div>

</div>

app/views/screening_rooms/index.html.erb
<div class="conatiner">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="movie-app-page-header">
        <h1>
          Manage Screening Rooms
        </h1>
      </div>
    </div>
  </div>
  <br>


  <div class="row">
    <div class="col-xs-12 col-md-5 col-md-offset-1">
      <h4>Current Screening Rooms</h4>
      <hr/>
      <ul class="list-group">
        <%= render @screening_rooms %>
      </ul>
    </div>

    <div class="col-xs-12 col-md-5">
      <h4>Add New Screening Room</h4>
      <hr/>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/screening_rooms/new.html.erb
<div class="page-header">
  <%= link_to screening_rooms_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New screening_room</h1>
</div>

<%= render 'form' %>

app/views/screening_rooms/show.html.erb
<div class="page-header">
  <%= link_to screening_rooms_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_screening_room_path(@screening_room), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show screening_room</h1>
</div>

<dl class="dl-horizontal">
  <dt>Theater number:</dt>
  <dd><%= @screening_room.theater_number %></dd>

  <dt>Seat quantity:</dt>
  <dd><%= @screening_room.seat_quantity %></dd>

  <dt>Movie theater:</dt>
  <dd><%= @screening_room.movie_theater_id %></dd>

</dl>