config/routes.rb
Rails.application.routes.draw do
  resources :ticket_offerings

  resources :bookings

  root to: "movie_theaters#show"

  resources :tickets

  resources :movies

  resources :showings

  resources :screening_rooms

  resources :movie_theaters
    get '/manage_theater_dashboard/:id',  :as => :theater_dashboard,
                                          :controller => :movie_theaters,
                                          :action => :dashboard

    get '/sales_information/:id',         :as => :sales_information,
                                          :controller => :movie_theaters,
                                          :action => :sales_dashboard

end

app/models/ticket_offering.rb
class TicketOffering < ActiveRecord::Base
  validates_presence_of :movie_theater, :name, :price
  belongs_to :movie_theater
  has_many :tickets
end

app/controllers/ticket_offerings_controller.rb
class TicketOfferingsController < ApplicationController
  before_action :set_ticket_offering, only: [:show, :edit, :update, :destroy]

  # GET /ticket_offerings
  # GET /ticket_offerings.json
  def index
    @ticket_offerings = TicketOffering.all
    @ticket_offering = TicketOffering.new
  end

  # GET /ticket_offerings/1
  # GET /ticket_offerings/1.json
  def show
  end

  # GET /ticket_offerings/new
  def new
    @ticket_offering = TicketOffering.new
  end

  # GET /ticket_offerings/1/edit
  def edit
  end

  # POST /ticket_offerings
  # POST /ticket_offerings.json
  def create
    @ticket_offering = TicketOffering.new(ticket_offering_params)

    respond_to do |format|
      if @ticket_offering.save
        format.html { redirect_to ticket_offerings_url, notice: 'Ticket offering was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /ticket_offerings/1
  # PATCH/PUT /ticket_offerings/1.json
  def update
    respond_to do |format|
      if @ticket_offering.update(ticket_offering_params)
        format.html { redirect_to ticket_offerings_url, notice: 'Ticket offering was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /ticket_offerings/1
  # DELETE /ticket_offerings/1.json
  def destroy
    @ticket_offering.destroy
    respond_to do |format|
      format.html { redirect_to ticket_offerings_url, notice: 'Ticket offering was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_offering
      @ticket_offering = TicketOffering.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_offering_params
      params.require(:ticket_offering).permit(:name, :price, :movie_theater_id)
    end

end

app/helpers/ticket_offerings_helper.rb
module TicketOfferingsHelper
end

app/views/ticket_offerings/_form.html.erb
<%= form_for(@ticket_offering, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @ticket_offering.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@ticket_offering.errors.count, "error") %> prohibited this ticket_offering from being saved:</h4>

      <ul>
      <% @ticket_offering.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :movie_theater_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :movie_theater_id,
        options_from_collection_for_select(MovieTheater.all,'id', 'name'),
        {},
        {:class => 'form-control'} %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn time-button" %>
      <% if @ticket_offering.persisted? %>
        <%= link_to "Delete Ticket Type", @ticket_offering, method: :delete,
            class: "btn time-button", data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/ticket_offerings/_ticket_offering.html.erb
<li class="list-group-item">
  <%= ticket_offering.name %> | <%= number_to_currency(ticket_offering.price) %>
  <%= link_to edit_ticket_offering_url(ticket_offering) do %>
    <%= icon('fa fa-pencil pull-right') %>
  <% end %>
</li>

app/views/ticket_offerings/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    <div class="movie-app-page-header">
      <h1>
        Edit Ticket Offerings
      </h1>
    </div>
  </div>
</div>
<br>
<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    <%= render 'form' %>
  </div>
</div>

app/views/ticket_offerings/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    <div class="movie-app-page-header">
      <h1>
        Manage Your Ticket Offerings
      </h1>
    </div>
  </div>
</div>
<br>


<div class="row">
  <div class="col-xs-12 col-md-5 col-md-offset-1">
    <h4>Current Ticket Offerings</h4>
    <hr/>
    <ul class="list-group">
      <%= render @ticket_offerings %>
    </ul>
  </div>

  <div class="col-xs-12 col-md-5">
    <h4>Create New Ticket Offering</h4>
    <hr/>
    <%= render 'form' %>
  </div>
</div>

app/views/ticket_offerings/new.html.erb
<div class="page-header">
  <%= link_to ticket_offerings_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New ticket_offering</h1>
</div>

<%= render 'form' %>

app/views/ticket_offerings/show.html.erb
<div class="page-header">
  <%= link_to ticket_offerings_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_ticket_offering_path(@ticket_offering), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show ticket_offering</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @ticket_offering.name %></dd>

  <dt>Price:</dt>
  <dd><%= @ticket_offering.price %></dd>

  <dt>Movie theater:</dt>
  <dd><%= @ticket_offering.movie_theater_id %></dd>

</dl>